### ISSUE TITLE
"Error 5: Access is Denied" when starting the TabMon Service

### ISSUE THREAD

**Issue by danjrahm** [tableau/TabMon#111]
Comments moved over from issue #99.

Hey Jmangue -

I'm having the same issues it seems. I've been trying to install TABMON and I'm getting the
"Error 5: Access is Denied" when starting the TabMon Service. Has there been any updates on this issue?

I've also confirmed that all of my machines are installed on the same domain. So that's not the issue here either.

**Comment by seanloftus** [comment]
Thank you Dan!  Here is the log file I see:

2017-03-09 16:41:36,570 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-03-09 16:41:36,606 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-03-09 16:41:36,607 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-03-09 16:41:36,731 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2017-03-09 16:41:36,829 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved '10.165.4.152' to 'tableaudev'.
2017-03-09 16:41:36,833 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\tableaudev', Writer='null', PollInterval='60', TableName='countersamples']
2017-03-09 16:41:36,833 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-03-09 16:41:36,834 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-03-09 16:41:36,834 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-03-09 16:41:36,840 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by danjrahm** [comment]
Looks like there are some invalid values in your TabMon config. Can you send that? Please scrub the passwords from it before sending. 

Thanks,
Dan

**Comment by seanloftus** [comment]
I've tried multiple configs.  Here's the latest:

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="10.165.4.152"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="XXXXX"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>

Thanks Dan!
Sena

**Comment by jmangue** [comment]
`FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"`

Did you change the password during installation?  If so, the password in your config needs to match.

**Comment by danjrahm** [comment]
Thanks Justin. Totally skipped over that line for some reason.

**Comment by seanloftus** [comment]
Thanks Justin.  I've fixed the password.  Now starting the service takes a
little longer but fails with the following log.  I've not changed the
Counters.config file at all since installing.  Not sure what path it's
looking for.  Any ideas now?

Thanks so much for your helpl!
Sean

2017-03-09 19:06:35,186 [5] INFO TabMon.Config.TabMonConfigReader - Loading
TabMon user configuration..
2017-03-09 19:06:35,217 [5] DEBUG TabMon.Config.TabMonConfigReader -
Loading database configuration..
2017-03-09 19:06:35,218 [5] INFO TabMon.Config.TabMonConfigReader -
Connecting to results database..
2017-03-09 19:06:35,402 [5] DEBUG TabMon.Helpers.HostnameHelper -
Successfully resolved '10.165.4.152' to 'tableaudev'.
2017-03-09 19:06:35,405 [5] INFO TabMon.Config.TabMonConfigReader -
Successfully loaded TabMon config options! [Host='Primary\tableaudev',
Writer='Database Writer (Postgres Driver)', PollInterval='60',
TableName='countersamples']
2017-03-09 19:06:35,406 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-03-09 19:06:35,407 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader
- Loading persistent performance counters from C:\Program Files
(x86)\TabMon\Config\Counters.config..
2017-03-09 19:06:35,410 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader
- Loading performance counters from C:\Program Files
(x86)\TabMon\Config\Counters.config..
2017-03-09 19:06:35,415 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader
- Successfully validated 'Config\Counters.config' against
'Resources\CountersConfig.xsd'.
2017-03-09 19:06:35,415 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader
- Loading Perfmon counters..
2017-03-09 19:06:40,124 [5] ERROR TabMon.TabMonAgent - Failed to initialize
counter sampler using counters from configuration file: The network path
was not found.

Aborting..
2017-03-09 19:06:40,125 [5] FATAL
Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start
successfully
Topshelf.TopshelfException: The service did not start successfully
(returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-03-09 19:06:40,130 [1] ERROR Topshelf.HostFactory - The service
terminated abnormally
System.NullReferenceException: Object reference not set to an instance of
an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at
Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by seanloftus** [comment]
Got it!  Using the IP address was causing a problem.  When I changed that
back to the server name, I'm able to start the service.  Thanks for you
help gentlemen!  Greatly appreciated!

Sean

**Comment by danjrahm** [comment]
No problem! Let us know if you have any other questions. 

Closing this out.

**Comment by seanloftus** [comment]
I do have one more question.  How long does it take to start collecting
data?  I can view data in the DBs, but it's not appearing on the reports.

[image: Inline image 1]

**Comment by danjrahm** [comment]
The poll interval should be every 60 seconds. If there is no data showing up in the reports you should try the following two steps.
1. Verify that the primary TabMon datasource in the workbook is pointed at the TabMon Postgres installation. If the datasource is not pointed at the TabMon Postgres server, please edit the connection.
2. Refresh the view. Sometimes new data is not displayed because when the query initially ran, there was no data in the DB. Refreshing the workbook will rerun the queries.

Let me know if this helps.

**Comment by seanloftus** [comment]
Thanks Daniel -

The TimeStamp offset was set to -7.  But that number was being subtracted
from the TimeStamp.  When I changed the sign to positive, all the data came
through.  Thanks for your help and the speedy responses!

Sean

**Comment by danjrahm** [comment]
No problem. I'll close this out now.

**Comment by danjrahm** [comment]
Nevermind. Thought I reopened it. Actually closing now.
