### ISSUE TITLE
TabMon service failed to start with multiple hosts

### ISSUE THREAD

**Issue by SamanthaGun** [tableau/TabMon#121]
Hi there

I added two clusters as below in my TabMon.config file. 

![image](https://user-images.githubusercontent.com/29054973/26964220-e14e8342-4d33-11e7-903f-4cca9ff0b558.png)

But after the above change, I am unable to start TabMon service. Excerpt of log file indicating the error is provided below.

2017-06-09 16:22:53,474 [8] INFO TabMon.TabMonAgent - TabMon stopped.
2017-06-09 16:22:53,474 [8] INFO Topshelf.Runtime.Windows.WindowsServiceHost - [Topshelf] Stopped
2017-06-09 16:22:56,521 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-06-09 16:22:56,537 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-06-09 16:22:56,552 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-06-09 16:22:56,693 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved '99.99.99.990' to 'SERVER1009'.
2017-06-09 16:22:56,693 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved '99.99.99.991' to 'SERVER991'.
2017-06-09 16:22:56,693 [5] INFO TabMon.Config.TabMonConfigReader - Successfully loaded TabMon config options! [Hosts='host server 1\SERVER1009,host server 2\SERVER991', Writer='Database Writer (Postgres Driver)', PollInterval='60', TableName='countersamples']
2017-06-09 16:22:56,693 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-06-09 16:22:56,693 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading persistent performance counters from D:\Tableau\TabMon\Config\Counters.config..
2017-06-09 16:22:56,693 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading performance counters from D:\Tableau\TabMon\Config\Counters.config..
2017-06-09 16:22:56,709 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Successfully validated 'Config\Counters.config' against 'Resources\CountersConfig.xsd'.
2017-06-09 16:22:56,709 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2017-06-09 16:22:57,037 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loaded 86 persistent Perfmon counters on SERVER1009.
**_2017-06-09 16:23:39,084 [5] ERROR TabMon.TabMonAgent - Failed to initialize counter sampler using counters from configuration file: The network path was not found.
Aborting.._**
2017-06-09 16:23:39,084 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-06-09 16:23:39,084 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

Any help would be greatly appreciated.

Thanks

**Comment by danjrahm** [comment]
There are 2 things that I can think of that would cause this.
1. The remote registry service is not enabled on one of the hosts.
2. The two hosts in the clusters are not in the same subnet.

To verify these options please go on both hosts and check that the Remote Registry service is enabled and gather the IP addresses. Once done, please send the information.

Thanks,
Dan

**Comment by SamanthaGun** [comment]
Hi Dan

Unfortunately, due to company security policy I am unable to provide IP addresses but it's most likely the item #2. 
I will try this on two servers that are in the same subnet.

Thanks
Sam

**Comment by jmangue** [comment]
@SamanthaGun did you have any luck with servers on the same subnet?

**Comment by danjrahm** [comment]
Due to inactivity, I am going to close this issue out.

**Comment by SamanthaGun** [comment]
Apologies for the issue was caused due to item #1. This item can be closed now.

**Comment by danjrahm** [comment]
Sounds great. Thank you.
