### ISSUE TITLE
Unable to Start Tabmon Service

### ISSUE THREAD

**Issue by RohanSingh24** [tableau/TabMon#125]
I installed Tabmon and Postgres. But I am not able to start the service. Here is the Tabmon log

```
2017-06-22 05:17:40,827 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-06-22 05:17:40,869 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-06-22 05:17:40,871 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-06-22 05:17:41,031 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
2017-06-22 05:17:41,045 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to 'EGVBIDEVRD01'.
2017-06-22 05:17:41,049 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\EGVBIDEVRD01', Writer='null', PollInterval='60', TableName='countersamples']
2017-06-22 05:17:41,049 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-06-22 05:17:41,049 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-06-22 05:17:41,050 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-06-22 05:17:41,058 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMon.TabMonAgent.Dispose()
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```
Looks like it's not able to connect to Postgres DB.
Here is the SQL for the DB
```
CREATE DATABASE "TabMon"
  WITH OWNER = tabmon
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'English_United States.1252'
       LC_CTYPE = 'English_United States.1252'
       CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE "TabMon" TO tabmon;
REVOKE ALL ON DATABASE "TabMon" FROM public;
```
I am attaching my PGSetup.ps1 and Tabmon.config file. FYI I chnaged the extension to .txt so that I can attach here
[PGSetup.txt](https://github.com/tableau/TabMon/files/1094429/PGSetup.txt)
[TabMon.txt](https://github.com/tableau/TabMon/files/1094430/TabMon.txt)

**Comment by RohanSingh24** [comment]
If i put `<OutputMode value="csv"/>` then I am able to start Tabmon service

**Comment by RohanSingh24** [comment]
I am able connect to PostgreSQL through [pgAdmin III] using tabmon credentials. But I don't see 'countersamples' table under [TabMon] db. When will the 'countersamples' table will be created?

**Comment by RohanSingh24** [comment]
Sorry my mistake. I was using latest release of npgsql package which is not supported by TabMon. Closing the issue
