### ISSUE TITLE
Error when starting Tabmon Services after installing on Tableau server

### ISSUE THREAD

**Issue by nborua** [tableau/TabMon#143]
Opening this as a copy of #128 which was closed. Unfortunately, I did not receive notification when a comment  was placed. I will be careful to monitor the Issue this time. Please help us on this. 

The Error from my logs are as below:

2017-08-07 12:30:41,777 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-08-07 12:30:41,808 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-08-07 12:30:41,808 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-08-07 12:30:43,870 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Failed to establish a connection to 'localhost'.
2017-08-07 12:30:43,870 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to 'ckt-qa-iftab-02'.
2017-08-07 12:30:43,870 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\ckt-qa-iftab-02', Writer='null', PollInterval='30', TableName='countersamples']
2017-08-07 12:30:43,870 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-08-07 12:30:43,870 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-08-07 12:30:43,870 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)

**Comment by nborua** [comment]
As for the query by Dan in Issue #128, yes it is in the same system as Postgres. Also the config file is as below. 

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="localhost"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>

**Comment by danjrahm** [comment]
Hello,

I am unable to see the configuration file.

GitHub will not allow us to post code unless we use the 'Insert Code' button in the toolbar or using triple backticks. Here is a link to their ['Creating and highlighting code blocks' help article](https://help.github.com/articles/creating-and-highlighting-code-blocks/).  

Once I have the config I should be able to figure out what is going wrong.

-Dan

**Comment by nborua** [comment]
`<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="localhost"/>
	<Host computerName="ckt-qa***" address="localhost"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>`

**Comment by danjrahm** [comment]
I am still unable to see it, can you attach the file?

**Comment by nborua** [comment]
[config.txt](https://github.com/tableau/TabMon/files/1330857/config.txt)

**Comment by nborua** [comment]
Adding below the latest error log:

2017-09-25 15:49:25,053 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-09-25 15:49:25,303 [5] FATAL TabMon.Config.TabMonConfigReader - Error loading TabMon.config: Unrecognized attribute 'computerName'. Note that attribute names are case-sensitive. (C:\Program Files (x86)\TabMon\Config\TabMon.config line 12))
2017-09-25 15:49:25,303 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-09-25 15:49:25,319 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by nborua** [comment]
Hi Dan, what should be the host computerName be? I am getting Unrecognized attribute for it. Thanks

**Comment by danjrahm** [comment]
Thanks for sending me the config file. I see the issue.

Currently we are in the middle of a release so the user guide and product are a bit out of sync. To fix this I would completely remove this line:

```xml
<Host computerName="ckt-qa***" address="localhost"/>
```

and edit the rest of the config to look like this:

```xml
<?xml version="1.0"?>
<!-- TabMon user settings: set these as required -->
<TabMonConfig xmlns="TabMon">
  <!-- Output mode.  "DB" for database, "CSV" for flat-file export -->
  <OutputMode value="db"/>
  <!-- Polling rate, in seconds -->
  <PollInterval value="60"/>
  <!-- Target cluster & host configuration -->
  <Clusters>
    <Cluster name="Primary">
      <Host name="ckt-qa***"/>
    </Cluster>
  </Clusters>
  <!-- Results output database Configuration-->
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    <!-- Generate indexes on service startup. -->
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    <!-- Automatically drop data rows older than the specified number of days.
         Set enabled="true" to turn this on. -->
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>
```

NOTE: "ckt-qa***" needs to be changed to reflect the actual computer name.

Please let me know if the suggestion above works.

Thanks,
Dan

**Comment by nborua** [comment]
Thanks Dan, now I am getting the below error:

2017-09-25 16:06:13,674 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-09-25 16:06:13,705 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-09-25 16:06:13,705 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-09-25 16:06:15,783 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Failed to establish a connection to 'localhost'.
2017-09-25 16:06:15,783 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'ckt-qa-iftab-02' to 'ckt-qa-iftab-02'.
2017-09-25 16:06:15,783 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\ckt-qa-iftab-02', Writer='null', PollInterval='60', TableName='countersamples']
2017-09-25 16:06:15,783 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-09-25 16:06:15,783 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-09-25 16:06:15,783 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-09-25 16:06:15,799 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by danjrahm** [comment]
Based on that exception it doesn't look like postgres is installed on the same machine as TabMon.

**Comment by nborua** [comment]
We have a single cluster setup on a single machine. I am able to connect to PostGreSQL on localhost port 8060 to workgroup database

**Comment by danjrahm** [comment]
The postgresql instance that TabMon writes to should not be the same as the Tableau Server postgres. Instead, a separate instance of postgres on a different host should be used.

To manually install Postgresql, please follow the instructions here:
https://tableau.github.io/TabMon/docs/tabmon_appendix_a

Once the separate Postgresql instance is installed please configure this portion of the TabMon config to match the new values.

```xml
<!-- Results output database Configuration-->
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    <!-- Generate indexes on service startup. -->
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    <!-- Automatically drop data rows older than the specified number of days.
         Set enabled="true" to turn this on. -->
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
```

**Comment by nborua** [comment]
I will do so and update you soon. Thanks

**Comment by nborua** [comment]
HI, I installed PostGres in a separate instance as per the link you have mentioned and setup the role and databases. However, I am still unable to start TabMon and get the below error:

2017-10-03 11:09:39,659 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-10-03 11:09:39,685 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-10-03 11:09:39,687 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-10-03 11:09:39,761 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28000: role "tabmon" is not permitted to log in
2017-10-03 11:09:39,762 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'ckt-qa-iftab-02' to 'ckt-qa-iftab-02'.
2017-10-03 11:09:39,765 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\ckt-qa-iftab-02', Writer='null', PollInterval='60', TableName='countersamples']
2017-10-03 11:09:39,766 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-10-03 11:09:39,766 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-10-03 11:09:39,767 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-10-03 11:09:39,774 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by nborua** [comment]
![postgres database](https://user-images.githubusercontent.com/29064200/31136006-d52c5420-a834-11e7-8dc3-4790ac24ced7.JPG)

**Comment by nborua** [comment]
I think I resolved it. Will let you know if its fixed

**Comment by danjrahm** [comment]
Thanks a lot for the update!

**Comment by nborua** [comment]
Thanks to you Dan for all the help.. the issue has been resolved now and I am able to start the TabMon. Thanks

**Comment by sankalpzpatnaik** [comment]
Hi nborua,
Could you please update how did you resolve the above issue?I have postgres as a separate instance and I am also getting the same error:
FATAL: 28000: role "tabmon" is not permitted to log in

Thanks.

**Comment by mattdotgreenlake** [comment]
barring the same/similar issue Dan helped with above, I think you may need to review the directions around assuring the tabmon process is running as a user with admin priveleges on the remote machine and that all the services on the remote machine are running to allow tabmon access to the remote tableau server instance.  See remote polling setup: https://tableau.github.io/TabMon/docs/tabmon_configure
