### ISSUE TITLE
Not able to start TabMon Services after the install.

### ISSUE THREAD

**Issue by HimanshuAggarwal18** [tableau/TabMon#159]
Hi,
We have a single server tableau installation. I installed TabMon to monitor the server vitals and other key metrics. But I am not able to start the TabMon service after the installation. It says "Windows could not start the TabMon Service on local computer. Error 5: Access is denied.

I will attach a copies of my config file as well as the Log file. File I have attached are from the two different options I tried basis some of the other thread on the similar issue but not able resolve yet.

Please advise. Thanks!

[TabMon_1.log](https://github.com/tableau/TabMon/files/1518782/TabMon_1.log)
[TabMon_config_1.txt](https://github.com/tableau/TabMon/files/1518783/TabMon_config_1.txt)
[TabMon_config_2.txt](https://github.com/tableau/TabMon/files/1518784/TabMon_config_2.txt)
[TabMon2.log.txt](https://github.com/tableau/TabMon/files/1518785/TabMon2.log.txt)

**Comment by danjrahm** [comment]
What version of TabMon is being run?

Also, is TabMon on the same computer as Tableau Server?

Thanks,
Dan

**Comment by HimanshuAggarwal18** [comment]
Yes TabJolt is installed on the same machine where Tableau server instance is running. And its TabMon 1.2 which I downloaded from https://github.com/tableau/TabMon/releases

**Comment by danjrahm** [comment]
Is TabMon config 1 or 2 being used?

**Comment by HimanshuAggarwal18** [comment]
I have tried with both the versions of TabMon Config file.. But no luck

**Comment by danjrahm** [comment]
Config 1 shouldn't work with version 1.2 at all. Can you try changing both 'computerName' and 'address' to 'localhost' and try running TabMon again?

**Comment by HimanshuAggarwal18** [comment]
I Have made the change you suggested but still not working. PLs see attached log files.

**Comment by HimanshuAggarwal18** [comment]
forgot the attachment

**Comment by HimanshuAggarwal18** [comment]
2017-11-30 15:17:57,509 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-11-30 15:17:57,540 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2017-11-30 15:17:57,540 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2017-11-30 15:17:59,618 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Failed to establish a connection to 'localhost'.
2017-11-30 15:17:59,618 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\localhost\localhost', Writer='null', PollInterval='60', TableName='countersamples']
2017-11-30 15:17:59,618 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-11-30 15:17:59,618 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2017-11-30 15:17:59,618 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-11-30 15:17:59,618 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by danjrahm** [comment]
Can you attach the new config? The current issue is that the Writer is 'null' and I need to figure out why that is.

-Dan

**Comment by HimanshuAggarwal18** [comment]
Apologies for replying late. Please find attached the config file.
[TabMon-config.txt](https://github.com/tableau/TabMon/files/1521907/TabMon-config.txt)

**Comment by danjrahm** [comment]
Is your postgres installation on the local computer and port 5432?

**Comment by HimanshuAggarwal18** [comment]
Issue is resolved now. My postgres DB has issue so I set it separately and created the database to capture the results. Its working fine and recording the results.

Is there a documentation available to understand the insights from sample workbook dashboard.

**Comment by danjrahm** [comment]
I'm glad that the issue was resolved!

We don't have a lot of documentation but there are some explanations in workbook. I also recommend joining our [Server & Online Administration forum](https://community.tableau.com/community/forums/server-administration). This is a good place to start any discussions about the findings.

Let me know if you have any other question. I'm going to close issue this now.
