### ISSUE TITLE
TabMon is not starting

### ISSUE THREAD

**Issue by ChandraGadde** [tableau/TabMon#168]
Hi,

We have the Tabmon application and it used to run. But for some reason it is not starting when i stopped it and trying to start it again.

Following is the error message i'm seeing in the logs:

2018-01-29 21:28:35,284 [1] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2018-01-29 21:28:35,299 [1] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2018-01-29 21:28:35,299 [1] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2018-01-29 21:28:35,502 [1] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wapp798p' to 'wapp798p'.
2018-01-29 21:28:35,502 [1] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wapp800p' to 'wapp800p'.
2018-01-29 21:28:35,502 [1] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'wapp801p' to 'wapp801p'.
2018-01-29 21:28:35,518 [1] INFO TabMon.Config.TabMonConfigReader - Successfully loaded TabMon config options! [Hosts='Primary\wapp798p,Primary\wapp800p,Primary\wapp801p', Writer='Database Writer (Postgres Driver)', PollInterval='30', TableName='countersamples']
2018-01-29 21:28:35,518 [1] INFO TabMon.TabMonAgent - Initializing TabMon..
2018-01-29 21:28:35,518 [1] INFO TabMon.TabMonAgent - Loading performance counters from E:\TabMon\Config\Counters.config..
2018-01-29 21:28:35,518 [1] DEBUG TabMon.CounterConfig.CounterConfigLoader - Successfully validated 'Config\Counters.config' against 'Resources\CountersConfig.xsd'.
2018-01-29 21:28:35,518 [1] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2018-01-29 21:28:45,549 [1] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 56 Perfmon counters on wapp798p.
2018-01-29 21:28:58,487 [1] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 95 Perfmon counters on wapp800p.
**2018-01-29 21:29:02,799 [1] ERROR Topshelf.Hosts.ConsoleRunHost - An exception occurred
System.InvalidOperationException: Category does not exist.
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounterCategory.CounterExists(String counterName, String categoryName, String machineName)
   at TabMon.Counters.Perfmon.PerfmonCounterLoader.LoadInstancesForCounter(Host host, String categoryName, String counterName, String unitOfMeasurement, IList`1 instanceFilters)
   at TabMon.CounterConfig.PerfmonCounterConfigReader.LoadCounters(XmlNode root, Host host)
   at TabMon.CounterConfig.CounterConfigLoader.Load(String pathToConfig, IEnumerable`1 hosts)
   at TabMon.TabMonAgent.Start()
   at TabMonService.TabMonServiceBootstrapper.Start(HostControl hostControl)
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()**

**Comment by danjrahm** [comment]
Hello,

Was TabMon updated while it was stopped? Also, what version of TabMon is being used?

Thanks,
Dan

**Comment by ChandraGadde** [comment]
hi it was unable to make contact with the primary and other nodes which is showing in the logs . it was working perfectly fine before . what i feel is there was windows patch upgrade to the production  happend a week ago and after that tabmon stopped running and coudn't communicate with other systems . the system cannot talk to each other on the specified Telnet port

**Comment by danjrahm** [comment]
That would make a lot of sense. I would work with your IT team to make sure you are able to remotely pull Perfmon counters. This article may be useful for troubleshooting remote Perfmon connectivity:
https://www.logicmonitor.com/support/monitoring/os-virtualization/troubleshooting-perfmon-access/

If there are any other TabMon questions please let me know.

**Comment by ChandraGadde** [comment]
Thankyou will look into it

**Comment by ChandraGadde** [comment]
2018-02-01 10:11:25,725 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:25,725 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:25,975 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:25,975 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'wapp798p' does not exist.
2018-02-01 10:11:26,241 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:26,241 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'wapp798p' does not exist.
2018-02-01 10:11:26,491 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:26,491 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'wapp798p' does not exist.
2018-02-01 10:11:26,741 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:26,741 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:27,006 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:27,006 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:27,256 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:27,256 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:27,506 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:27,506 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:27,772 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:27,772 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'wapp798p' does not exist.
2018-02-01 10:11:28,022 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:28,022 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'wapp798p' does not exist.
2018-02-01 10:11:28,272 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:28,272 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'wapp798p' does not exist.
2018-02-01 10:11:28,538 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:28,538 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'wapp798p' does not exist.
2018-02-01 10:11:28,788 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:28,788 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'wapp798p' does not exist.
2018-02-01 10:11:29,038 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp798p': Access is denied
2018-02-01 10:11:29,038 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'wapp798p' does not exist.
2018-02-01 10:11:29,038 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 Perfmon counters on wapp798p.
2018-02-01 10:11:29,538 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:29,538 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:29,803 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:29,803 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'wapp800p' does not exist.
2018-02-01 10:11:30,053 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:30,053 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'wapp800p' does not exist.
2018-02-01 10:11:30,334 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:30,334 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'wapp800p' does not exist.
2018-02-01 10:11:30,584 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:30,584 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:30,834 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:30,834 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:31,084 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:31,084 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:31,334 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:31,350 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:31,584 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:31,584 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'wapp800p' does not exist.
2018-02-01 10:11:31,866 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:31,866 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'wapp800p' does not exist.
2018-02-01 10:11:32,350 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:32,350 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'wapp800p' does not exist.
2018-02-01 10:11:32,647 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:32,647 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'wapp800p' does not exist.
2018-02-01 10:11:32,928 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:32,928 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'wapp800p' does not exist.
2018-02-01 10:11:33,178 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp800p': Access is denied
2018-02-01 10:11:33,178 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'wapp800p' does not exist.
2018-02-01 10:11:33,178 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 0 Perfmon counters on wapp800p.
2018-02-01 10:11:33,663 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:33,663 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Free Space' in category 'LogicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:33,913 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:33,913 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Committed Bytes In Use' in category 'Memory' on host 'wapp801p' does not exist.
2018-02-01 10:11:34,163 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:34,163 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Received/sec' in category 'Network Interface' on host 'wapp801p' does not exist.
2018-02-01 10:11:34,413 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:34,413 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Bytes Sent/sec' in category 'Network Interface' on host 'wapp801p' does not exist.
2018-02-01 10:11:34,663 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:34,663 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Read Time' in category 'PhysicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:34,913 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:34,913 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Disk Write Time' in category 'PhysicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:35,163 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:35,163 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Current Disk Queue Length' in category 'PhysicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:35,413 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:35,413 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Write Bytes/sec' in category 'PhysicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:35,663 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:35,663 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Disk Read Bytes/sec' in category 'PhysicalDisk' on host 'wapp801p' does not exist.
2018-02-01 10:11:35,913 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:35,913 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Process' on host 'wapp801p' does not exist.
2018-02-01 10:11:36,163 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:36,163 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Thread Count' in category 'Process' on host 'wapp801p' does not exist.
2018-02-01 10:11:36,413 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:36,413 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Working Set' in category 'Process' on host 'wapp801p' does not exist.
2018-02-01 10:11:36,663 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:36,663 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter '% Processor Time' in category 'Processor' on host 'wapp801p' does not exist.
2018-02-01 10:11:36,913 [5] ERROR TabMon.Counters.Perfmon.PerfmonCounterLoader - Could not communicate with Perfmon on target host 'wapp801p': Access is denied
2018-02-01 10:11:36,913 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounterLoader - Counter 'Processes' in category 'System' on host 'wapp801p' does not exist.

**Comment by ChandraGadde** [comment]
here are the recent log files to be more precised "access Denied"

**Comment by ChandraGadde** [comment]
can you help me with the steps on  remotely pull Perfmon counters from the workers

**Comment by danjrahm** [comment]
Hello, 

It look like all of these errors are due to permissions. To begin troubleshooting, please try following the steps below:

1. Stop TabMon.

2. Ensure that the “Remote Registry” and “Performance Logs & Alerts” Windows services are running and set to Start Mode: Automatic on all remote machines.

3. On the TabMon machine, go to Services and right click and select properties for “TabMon”. Make sure that the account for logon has privileges on the machine you would like to remotely connect to. Specifically, the service account must:
     i. On each server you wish to remotely monitor: have admin permissions or be a member of the 
     “Performance Monitor Users” and “Performance Log Users” domain group

     ii. On the machine where TabMon is installed: have permissions to run as a service and write to the 
     TabMon install directory.

4. Start TabMon. 

Please let me know the results of these steps.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello, 

I'm reaching out to see if these steps helped. 

-Dan

**Comment by danjrahm** [comment]
Closing due to inactivity.
