### ISSUE TITLE
No data on the Dashboard

### ISSUE THREAD

**Issue by danjrahm** [tableau/TabMon#209]
Comment from mhelfand in issue #208.

```
I am also not getting any data information. Running v1.3 and have Desktop 10.5.4
```

**Comment by danjrahm** [comment]
Hello mhelfand,

In order to begin this investigation I will need some more information:

1. What version of Tableau Server are you collecting information from?
2. What version of the TabMon.config are you using?
3. What version of the workbook are you using?

Once I have the answers to these questions I should be able to recommend a solution.

-Dan

**Comment by danjrahm** [comment]
From a discussion I had with mhelfand:

TabMon log showed that there was an exception to while trying to write to the database:
```
2019-01-08 11:44:08,956 [6] DEBUG DataTableWriter.DbTableManager - Database table 'countersamples' already exists; skipping creation.
2019-01-08 11:44:09,210 [6] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
System.ArgumentException: Cannot add non-nullable columns to an existing database table!
Parameter name: column
   at DataTableWriter.Adapters.DbAdapter.AddColumnsToTableToMatchSchema(String tableName, DataTable schema)
   at DataTableWriter.DbTableManager.UpdateTableToMatchSchema(IDbAdapter adapter, DataTable schema)
   at DataTableWriter.DbTableManager.InitializeTable(IDbAdapter adapter, DataTable schema, DbTableInitializationOptions tableInitializationOptions)
   at DataTableWriter.Writers.DataTableDbWriter.Write(DataTable table)
   at TabMon.TabMonAgent.Poll()
   at TabMon.TabMonAgent.OnTimer(Object stateInfo)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at <URL>?domain=system.threading.executioncontext.run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

This indicates that the table was not properly created. To resolve the issue, we dropped the table and let TabMon rebuild it. Instructions are below:
