### ISSUE TITLE
Unable to start TabMon services after editing config file

### ISSUE THREAD

**Issue by Brian3thousand** [tableau/TabMon#243]
Hi all,

I tried to peruse a lot of similar reported issues and attempted to make some of the noted recommendations but I'm still unable to get TabMon services to start after I edit the config file.
Pre-reqs successfully completed: 
1. opened Tableau Server JMX ports on node I want to monitor (for now just 1 single node)
2. configured readonly user for postgress access on node I want to monitor
3. Ensured remote registry and performance logs and alerts are running and set to automatic on the nodes
4.Verified account for logon has proper privileges on the servers
5. I even edited line 11 that says <Host computerNAME ="XYZ" address="localhost" specifyPorts="false"/> to just be <Host name="XYZ"/>

I'm positive there is only 1 domain in play and that I'm using the correct FQDN.

What I see in Windows when I try to start TabMon services is: "the Error 5 Access is denied" note and in the TabMon log itself I see this -

2020-04-21 14:28:49,859 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2020-04-21 14:28:49,891 [5] FATAL TabMon.Config.TabMonConfigReader - Error loading TabMon.config: Required attribute 'address' not found. (C:\Tableau\Config\TabMon.config line 11))
2020-04-21 14:28:49,891 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2020-04-21 14:28:49,899 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by Brian3thousand** [comment]
Welp, for whatever reason it worked after I uninstalled and re-installed. Not sure what was messed up the 1st time around but whatevz!
