### ISSUE TITLE
"instance" column length too short in GenerateSchema

### ISSUE THREAD

**Issue by rancidx** [tableau/TabMon#36]
Getting the following error in the log file:

    2016-01-13 14:06:01,465 [5] INFO TabMon.TabMonAgent - TabMon initialized!  Starting performance counter polling..
    2016-01-13 14:06:01,480 [5] INFO Topshelf.Runtime.Windows.WindowsServiceHost - [Topshelf] Started
    2016-01-13 14:06:01,480 [6] INFO TabMon.Sampler.CounterSampler - Polling..
    2016-01-13 14:06:01,527 [6] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
    System.ArgumentException: Cannot set column 'instance'. The value violates the MaxLength limit of this column.
       at System.Data.DataColumn.CheckMaxLength(DataRow dr)
       at System.Data.DataTable.RaiseRowChanging(DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, Boolean fireEvent)
       at System.Data.DataTable.SetNewRecordWorker(DataRow row, Int32 proposedRecord, DataRowAction action, Boolean isInMerge, Boolean suppressEnsurePropertyChanged, Int32 position, Boolean fireEvent, Exception& deferredException)
       at System.Data.DataTable.InsertRow(DataRow row, Int64 proposedID, Int32 pos, Boolean fireEvent)
       at TabMon.Sampler.CounterSampler.SampleAll()
       at TabMon.TabMonAgent.Poll(Object stateInfo)
       at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()
       at System.Threading.TimerQueue.AppDomainTimerCallback()

I believe to have tracked the cause down to the following line in TabMon.Sampler.CounterSampler.GenerateSchema()
```csharp
generatedSchema.Columns.Add(BuildColumnMetadata("instance", "System.String", true, 64));
```
The offending counter instance name seems to be "*HP NC375i Integrated Quad Port Multifunction Gigabit Server Adapter*" at 67 characters long, exceeding the maxLength of 64.

Explicitly listing the Network Interface counter instances without including the one mentioned above results in TabMon running without issues.

**Comment by danjrahm** [comment]
Hey,

Thanks for pointing this out. It looks like we are going to have to figure out the max instance length before generating the column. 

I've changed this to a bug and added a milestone.

Best,
Dan

**Comment by jmangue** [comment]
Closing this out.
