### ISSUE TITLE
TabMon Postgres - value violates the Max Length limit

### ISSUE THREAD

**Issue by GirlMeetsData** [tableau/TabMon#56]
I enabled Tableau server's JMX ports and installed TabMon & the Postgres database. When I went to execute TabMon it was able to successfully open the JMX connections and loaded counters. Once TabMon was initialized it threw the below error. 

I was wondering if anyone else experienced this and had a resolution. Or, if anyone has changed the lengths of fields in TabMon's Postgres

2016-03-28 20:38:11,361 [6] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
System.ArgumentException: Cannot set column 'machine'. The value violates the MaxLength limit of this column.
   at System.Data.DataColumn.CheckMaxLength(DataRow dr)
   at System.Data.DataTable.RaiseRowChanging(DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, Boolean fireEvent)
   at System.Data.DataTable.SetNewRecordWorker(DataRow row, Int32 proposedRecord, DataRowAction action, Boolean isInMerge, Boolean suppressEnsurePropertyChanged, Int32 position, Boolean fireEvent, Exception& deferredException)
   at System.Data.DataTable.InsertRow(DataRow row, Int64 proposedID, Int32 pos, Boolean fireEvent)
   at TabMon.Sampler.CounterSampler.SampleAll()
   at TabMon.TabMonAgent.Poll(Object stateInfo)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by GirlMeetsData** [comment]
After investigating this we realized it wasn't due to a Postgres constraint on the column length but one set in the C++ code that sets the max length for 'machine' to 16. Is there a reason this is limited to 16?

**Comment by jmangue** [comment]
Hi --

The reason that column is limited to 16 is because the max NETBIOS computer name length in Windows is 15 characters.  See [Microsoft KB article](https://support.microsoft.com/en-us/kb/909264).

I'm curious how you're exceeding this -- do you have unicode characters in the hostname?

**Comment by GirlMeetsData** [comment]
We did use " - "
It's a VM, would that make a difference?

**Comment by jmangue** [comment]
It should be trivial to make the max length for this column bigger, setting this as a bug to be addressed.

**Comment by GirlMeetsData** [comment]
Sweet, thanks!

**Comment by jmangue** [comment]
Fixed in #92 -- column length has been extended to max Windows DNS length (as opposed to max NETBIOS length).
