### ISSUE TITLE
Cannot set column 'instance'. The value violates the MaxLength limit of this column

### ISSUE THREAD

**Issue by Hucklerl** [tableau/TabMon#63]
"2016-05-09 09:11:20,519 [5] INFO TabMon.CounterConfig.CounterConfigLoader - Loaded 74 MBean counters on n4dtab1.
2016-05-09 09:11:20,519 [5] DEBUG TabMon.TabMonAgent - Successfully loaded 373 counters from configuration file.
2016-05-09 09:11:20,535 [5] DEBUG TabMon.Sampler.CounterSampler - Dynamically built result schema 'countersamples'. [48 columns]
2016-05-09 09:11:20,535 [5] INFO TabMon.TabMonAgent - TabMon initialized!  Starting performance counter polling..
2016-05-09 09:11:20,535 [5] INFO Topshelf.Runtime.Windows.WindowsServiceHost - [Topshelf] Started
2016-05-09 09:11:20,535 [6] INFO TabMon.Sampler.CounterSampler - Polling..
2016-05-09 09:11:20,550 [6] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
System.ArgumentException: Cannot set column 'instance'. The value violates the MaxLength limit of this column.**
   at System.Data.DataColumn.CheckMaxLength(DataRow dr)
   at System.Data.DataTable.RaiseRowChanging(DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, Boolean fireEvent)
   at System.Data.DataTable.SetNewRecordWorker(DataRow row, Int32 proposedRecord, DataRowAction action, Boolean isInMerge, Boolean suppressEnsurePropertyChanged, Int32 position, Boolean fireEvent, Exception& deferredException)
   at System.Data.DataTable.InsertRow(DataRow row, Int64 proposedID, Int32 pos, Boolean fireEvent)
   at TabMon.Sampler.CounterSampler.SampleAll()
   at TabMon.TabMonAgent.Poll(Object stateInfo)"

Hi , I am getting the error stated above, but would have not idea where to begin resolving. Its a big ask, but you help would be much appreciated . 

Many thanks

**Comment by jmangue** [comment]
Hi Hucklerl, this looks like a bug..  One of the PerfMon counters you're polling has an instance name that is unexpectedly long.  If you can find out which counter it is, removing it from monitoring in Counters.config would be a workaround.  Usually the longest instance names we see are in network adapters so I'd try to start there.

Flagging this as a bug to be fixed in the code.

**Comment by Hucklerl** [comment]
Hi 

Thanks for the response . We have found the issue and have renamed the network adapters and now waiting for the server to reboot for the new name to cascade through the registers.
 
Regards

**Comment by jmangue** [comment]
Fixed in #92 -- this column length has been extended to the max allowable length.
