### ISSUE TITLE
TabMon can't start because Cannot set column 'machine'

### ISSUE THREAD

**Issue by Gavin-Zhao** [tableau/TabMon#64]
log:

2016-05-03 12:43:09,094 [5] INFO Topshelf.Runtime.Windows.WindowsServiceHost - [Topshelf] Started
2016-05-03 12:43:09,094 [6] INFO TabMon.Sampler.CounterSampler - Polling..
2016-05-03 12:43:09,109 [6] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service threw an unhandled exception
System.ArgumentException: **Cannot set column 'machine'. The value violates the MaxLength limit of this column.**
   at System.Data.DataColumn.CheckMaxLength(DataRow dr)
   at System.Data.DataTable.RaiseRowChanging(DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, Boolean fireEvent)
   at System.Data.DataTable.SetNewRecordWorker(DataRow row, Int32 proposedRecord, DataRowAction action, Boolean isInMerge, Boolean suppressEnsurePropertyChanged, Int32 position, Boolean fireEvent, Exception& deferredException)
   at System.Data.DataTable.InsertRow(DataRow row, Int64 proposedID, Int32 pos, Boolean fireEvent)
   at TabMon.Sampler.CounterSampler.SampleAll()
   at TabMon.TabMonAgent.Poll(Object stateInfo)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
****

**Comment by GirlMeetsData** [comment]
See: https://github.com/tableau/TabMon/issues/56

**Comment by Gavin-Zhao** [comment]
oh, I used '-'.
but if the BIOS computer name can't be changed, do we have other way to resolve it.

**Comment by GirlMeetsData** [comment]
Yes you can rename your server. That's what we did. If you don't know how, ask your ops team. Good luck!

**Comment by jmangue** [comment]
Thanks for helping out, GirlMeetsData!

Closing this out.
