### ISSUE TITLE
TabMon Log error - Unable to start the tabmon service if I enable remote logon

### ISSUE THREAD

**Issue by Shobananpa** [tableau/TabMon#76]
Hi Team,

I'm seeing this error on our production server, where we have installed tabmon on gateway server and enabled remote polling on 2 of our worker nodes & backup primary.

Tabmon runs only when I enable log on as local system account and not when I select This account on the Logon tab in TabMon properties.

Is there any permission issue that's causing remote logon stopping.

Windows eventlog
The TabMon service terminated with the following error: 
Access is denied.
Windows Application eventlog
Service cannot be started. System.InvalidOperationException: Category does not exist.
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounterCategory.CounterExists(String counterName, String categoryName, String machineName)
   at TabMon.Counters.Perfmon.PerfmonCounterLoader.LoadInstancesForCounter(Host host, String categoryName, String counterName, String unitOfMeasurement, IList`1 instanceFilters)
   at TabMon.CounterConfig.PerfmonCounterConfigReader.LoadCounters(XmlNode root, Host host)
   at TabMon.CounterConfig.CounterConfigLoader.Load(String pathToConfig, IEnumerable`1 hosts)
   at TabMon.TabMonAgent.Start()
   at TabMonService.TabMonServiceBootstrapper.Start(HostControl hostControl)
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Start(HostControl hostControl)
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Ob...

**Comment by jmangue** [comment]
Closing this one out in favor of #78
